### ISSUE TITLE
macOS PySoar v 0.57.1 not downloading IGC

### ISSUE THREAD

**Issue by jvanakker** [GliderGeek/PySoar#147]
While main_pysoar.app actually runs fine, it seems to have these issues:
- No texts on UI buttons
- Does not start downlaoding IGC's even though it says "URL correct"
- Does not generate output spreadsheet file

Tried with URL:
https://www.soaringspot.com/en_gb/nationale-kampioenschappen-zweefvliegen-2019/results/clubklasse/task-3-on-2019-05-25/daily

**Comment by GliderGeek** [comment]
@jvanakker: thanks for reporting. I know that the UI has some problems on mac unfortunately. which OS are you running? also can you send a screenshot for the wrong buttons?

despite the problems with UI, the code should work correctly, will investigate with your URL.

**Comment by GliderGeek** [comment]
i have reproduced the problem with the buttons on Mac OS 10.14.4.

**Comment by GliderGeek** [comment]
it seems to me that these are only UI problems, since when i run pysoar on the commandline i dont have any problems.

you can run pysoar from the commandline as follows:
`main_pysoar.app/Contents/MacOS/main_pysoar URL`

in your case:
`main_pysoar.app/Contents/MacOS/main_pysoar https://www.soaringspot.com/en_gb/nationale-kampioenschappen-zweefvliegen-2019/results/clubklasse/task-3-on-2019-05-25/daily`

this is far from ideal, but might help out when the UI is a problem (and this has been a problem already a lot of times....)

attached is the produces xlsx
[Analysis_PySoar.xlsx](https://github.com/GliderGeek/PySoar/files/3224912/Analysis_PySoar.xlsx)

**Comment by jvanakker** [comment]
This was on 10.14.5. Thanks, will try command line when I have time.
(BTW, buttons UI problem goes away when you switch the window to full screen and back).

**Comment by GliderGeek** [comment]
i have released a new version: v0.58.0, which hopefully has solved the GUI issues on mac OS. please let me know if this is not the case
